### ISSUE TITLE
Minify production output

### ISSUE THREAD

**Issue by joshhornby** [loganhenson/laravel-elm-npm#2]
Hi,

Thanks for this library, how would you recommend we minify the output of elm.js in production?

**Comment by loganhenson** [comment]
Hey @joshhornby (sorry for late response),

This supporting library has undergone quite a bit up change/upgrading lately, and now is a bit more streamlined. It integrates with Laravel mix, and auto minifies the output when in production.

https://github.com/tighten/laravel-elm is where most of the public work is being done if you are still interested in Laravel + Elm!
